export const languages = ["ru", "hy", "en"];
export const tr = (ru, hy, en) => ({ ru, hy, en });
const same = (s) => tr(s, s, s);
export const ui = {
  ru: {
    home: "Главная",
    slots: "Слоты",
    promotions: "Акции",
    help: "Поддержка",
    login: "Войти",
    register: "Регистрация",
    all: "Все игры",
    providers: "Провайдеры",
    featured: "В центре внимания",
    collection: "Ваша следующая любимая игра",
    search: "Найти игру",
    empty: "Ничего не найдено. Попробуйте другой фильтр.",
    play: "Играть",
    details: "Подробнее",
    random: "Не знаете, во что поиграть?",
    randomText: "Доверьтесь льву. Один клик — новая подборка.",
    spin: "Крутить",
    spinning: "Лев выбирает…",
    selection: "Выбор льва",
    again: "Попробовать ещё",
    telegram: "Написать в Telegram",
    age: "Вам уже исполнилось 18 лет?",
    ageText:
      "Этот сайт предназначен только для совершеннолетних. Играйте ответственно.",
    yes: "Да, мне есть 18",
    no: "Мне нет 18",
    denied: "Доступ доступен только с 18 лет.",
    back: "Назад",
    name: "Имя",
    phone: "Номер телефона",
    handle: "Telegram",
    consent:
      "Согласен с обработкой данных согласно политике конфиденциальности",
    submit: "Сохранить и перейти в Telegram",
    saved: "Заявка сохранена",
    sendHint: "Отправьте подготовленное сообщение оператору в Telegram.",
    error: "Не удалось выполнить запрос. Попробуйте ещё раз.",
    close: "Закрыть",
    external: "Открыть в новой вкладке",
    frameHelp: "Если платформа не загрузилась, откройте её в новой вкладке.",
    unavailable:
      "Ссылка на эту игру скоро появится. Пока можно посмотреть другие игры.",
    demo: "Превью",
    about: "О нас",
    privacy: "Конфиденциальность",
    terms: "Условия использования",
    app: "Скачать приложение",
    download: "Скачать",
    soon: "Ссылка на приложение скоро появится",
    rights: "Все права защищены.",
    responsible:
      "Игра — развлечение, а не способ заработка. Участвуйте ответственно. 18+",
    next: "Следующий слайд",
    prev: "Предыдущий слайд",
    pause: "Пауза",
    resume: "Продолжить",
    slide: "Слайд",
    catalog: "Каталог игр",
    offers: "Особые предложения",
    questions: "Чем можем помочь?",
    more: "Смотреть все",
    category: "Категория",
    notFound: "Страница не найдена",
    latest: "Новости",
    bonus: "Бонус",
    promotion: "Акция",
    news: "Новость",
    offer: "Предложение",
    pending: "Сохраняем…",
  },
  en: {
    home: "Home",
    slots: "Slots",
    promotions: "Promotions",
    help: "Support",
    login: "Log in",
    register: "Register",
    all: "All games",
    providers: "Providers",
    featured: "In the spotlight",
    collection: "Your next favourite game",
    search: "Find a game",
    empty: "No results. Try a different filter.",
    play: "Play",
    details: "Details",
    random: "Not sure what to play?",
    randomText: "Let the lion choose. One click, a fresh selection.",
    spin: "Spin",
    spinning: "The lion is choosing…",
    selection: "The lion’s picks",
    again: "Try again",
    telegram: "Message on Telegram",
    age: "Are you 18 or older?",
    ageText: "This website is for adults only. Please play responsibly.",
    yes: "Yes, I am 18+",
    no: "I am under 18",
    denied: "Access is available to adults aged 18 and over.",
    back: "Back",
    name: "Name",
    phone: "Phone number",
    handle: "Telegram",
    consent: "I agree to data processing under the privacy policy",
    submit: "Save and continue to Telegram",
    saved: "Request saved",
    sendHint: "Send the prepared message to the operator in Telegram.",
    error: "The request failed. Please try again.",
    close: "Close",
    external: "Open in a new tab",
    frameHelp: "If the platform does not load, open it in a new tab.",
    unavailable:
      "This game link is coming soon. Explore other games in the meantime.",
    demo: "Preview",
    about: "About us",
    privacy: "Privacy",
    terms: "Terms of use",
    app: "Get the app",
    download: "Download",
    soon: "The app link is coming soon",
    rights: "All rights reserved.",
    responsible: "Gaming is entertainment, not income. Play responsibly. 18+",
    next: "Next slide",
    prev: "Previous slide",
    pause: "Pause",
    resume: "Resume",
    slide: "Slide",
    catalog: "Game library",
    offers: "Special offers",
    questions: "How can we help?",
    more: "View all",
    category: "Category",
    notFound: "Page not found",
    latest: "News",
    bonus: "Bonus",
    promotion: "Promotion",
    news: "News",
    offer: "Offer",
    pending: "Saving…",
  },
  hy: {
    home: "Գլխավոր",
    slots: "Սլոթեր",
    promotions: "Ակցիաներ",
    help: "Աջակցություն",
    login: "Մուտք",
    register: "Գրանցվել",
    all: "Բոլոր խաղերը",
    providers: "Մատակարարներ",
    featured: "Ուշադրության կենտրոնում",
    collection: "Ձեր հաջորդ սիրելի խաղը",
    search: "Գտնել խաղը",
    empty: "Արդյունքներ չկան։ Փորձեք այլ զտիչ։",
    play: "Խաղալ",
    details: "Մանրամասն",
    random: "Չգիտե՞ք՝ ինչ խաղալ",
    randomText: "Վստահեք առյուծին։ Մեկ սեղմում՝ նոր ընտրանի։",
    spin: "Պտտել",
    spinning: "Առյուծն ընտրում է…",
    selection: "Առյուծի ընտրությունը",
    again: "Փորձել կրկին",
    telegram: "Գրել Telegram-ում",
    age: "Դուք արդեն 18 տարեկան ե՞ք",
    ageText:
      "Այս կայքը նախատեսված է միայն չափահասների համար։ Խաղացեք պատասխանատու։",
    yes: "Այո, ես 18+ եմ",
    no: "Ես 18-ից փոքր եմ",
    denied: "Մուտքը հասանելի է միայն 18 տարեկանից։",
    back: "Հետ",
    name: "Անուն",
    phone: "Հեռախոսահամար",
    handle: "Telegram",
    consent:
      "Համաձայն եմ տվյալների մշակմանը՝ գաղտնիության քաղաքականության համաձայն",
    submit: "Պահպանել և անցնել Telegram",
    saved: "Հայտը պահպանված է",
    sendHint: "Ուղարկեք պատրաստված հաղորդագրությունը օպերատորին Telegram-ում։",
    error: "Հարցումը ձախողվեց։ Փորձեք կրկին։",
    close: "Փակել",
    external: "Բացել նոր ներդիրում",
    frameHelp: "Եթե հարթակը չի բեռնվում, բացեք այն նոր ներդիրում։",
    unavailable: "Այս խաղի հղումը շուտով կհայտնվի։ Մինչ այդ դիտեք այլ խաղեր։",
    demo: "Նախադիտում",
    about: "Մեր մասին",
    privacy: "Գաղտնիություն",
    terms: "Օգտագործման պայմաններ",
    app: "Ներբեռնել հավելվածը",
    download: "Ներբեռնել",
    soon: "Հավելվածի հղումը շուտով կհայտնվի",
    rights: "Բոլոր իրավունքները պաշտպանված են։",
    responsible:
      "Խաղը զվարճանք է, ոչ թե եկամտի աղբյուր։ Խաղացեք պատասխանատու։ 18+",
    next: "Հաջորդ սլայդը",
    prev: "Նախորդ սլայդը",
    pause: "Դադար",
    resume: "Շարունակել",
    slide: "Սլայդ",
    catalog: "Խաղերի կատալոգ",
    offers: "Հատուկ առաջարկներ",
    questions: "Ինչո՞վ կարող ենք օգնել",
    more: "Դիտել բոլորը",
    category: "Կատեգորիա",
    notFound: "Էջը չի գտնվել",
    latest: "Նորություններ",
    bonus: "Բոնուս",
    promotion: "Ակցիա",
    news: "Նորություն",
    offer: "Առաջարկ",
    pending: "Պահպանվում է…",
  },
};
const seo = { title: same(""), description: same(""), keywords: same("") };
const item = (id, title, extra = {}) => ({
  id,
  slug: id,
  title,
  description: same(""),
  seo: structuredClone(seo),
  enabled: true,
  ...extra,
});
export const initialContent = {
  version: 2,
  settings: {
    brand: "YvnBet",
    logo: "/images/wordmark.webp",
    lion: "/images/lion.svg",
    telegram: "yvnbet",
    telegramText: tr(
      "Здравствуйте! Нужна помощь.",
      "Բարև։ Օգնության կարիք ունեմ։",
      "Hello! I need help.",
    ),
    loginUrl: "https://ggplus.pro",
    loginMode: "iframe",
    appUrl: "",
    siteUrl: "",
    indexable: false,
    ogImage: "/images/hero.webp",
    defaultLanguage: "ru",
    sliderSeconds: 7,
  },
  interface: ui,
  seo: {
    home: {
      title: tr(
        "YvnBet — ваша территория игры",
        "YvnBet — ձեր խաղային տարածքը",
        "YvnBet — your world of play",
      ),
      description: tr(
        "Откройте каталог игр, провайдеров и специальных предложений YvnBet.",
        "Բացահայտեք YvnBet-ի խաղերը, մատակարարներն ու հատուկ առաջարկները։",
        "Explore the YvnBet collection of games, providers and special offers.",
      ),
      keywords: same("YvnBet, slots, games"),
    },
    slots: {
      title: tr(
        "Каталог игр — YvnBet",
        "Խաղերի կատալոգ — YvnBet",
        "Game library — YvnBet",
      ),
      description: tr(
        "Найдите игру в каталоге YvnBet: поиск, категории и фильтры по провайдерам.",
        "Գտեք խաղը YvnBet-ում՝ որոնման, կատեգորիաների և մատակարարների զտիչներով։",
        "Find your game in the YvnBet library using search, categories and provider filters.",
      ),
      keywords: same("YvnBet, games, slots"),
    },
    promotions: {
      title: tr(
        "Акции и новости — YvnBet",
        "Ակցիաներ և նորություններ — YvnBet",
        "Promotions and news — YvnBet",
      ),
      description: tr(
        "Новости, действующие акции и специальные предложения YvnBet с подробными условиями.",
        "YvnBet-ի նորությունները, ընթացիկ ակցիաներն ու հատուկ առաջարկները՝ մանրամասն պայմաններով։",
        "YvnBet news, current promotions and special offers with detailed terms.",
      ),
      keywords: same("YvnBet, promotions, news"),
    },
    help: {
      title: tr(
        "Поддержка и FAQ — YvnBet",
        "Աջակցություն և ՀՏՀ — YvnBet",
        "Support and FAQ — YvnBet",
      ),
      description: tr(
        "Ответы на вопросы о регистрации и запуске игр. Свяжитесь с поддержкой YvnBet в Telegram.",
        "Գրանցման և խաղերի գործարկման հարցերի պատասխաններ։ Կապվեք YvnBet աջակցության հետ Telegram-ում։",
        "Answers about registration and game access. Contact YvnBet support on Telegram.",
      ),
      keywords: same("YvnBet, support, FAQ"),
    },
    app: {
      title: tr("Приложение YvnBet", "YvnBet հավելված", "YvnBet app"),
      description: tr(
        "Информация о мобильном приложении YvnBet и доступных способах скачивания.",
        "Տեղեկություն YvnBet բջջային հավելվածի և ներբեռնման եղանակների մասին։",
        "Information about the YvnBet mobile app and available downloads.",
      ),
      keywords: same("YvnBet, mobile, app"),
    },
  },
  providers: [
    item("amusnet", same("Amusnet"), { logo: "", url: "", mode: "external" }),
    item("pragmatic-play", same("Pragmatic Play"), {
      logo: "",
      url: "",
      mode: "external",
    }),
    item("amatic", same("Amatic"), { logo: "", url: "", mode: "external" }),
  ],
  categories: [
    item("slots", tr("Слоты", "Սլոթեր", "Slots")),
    item("table", tr("Настольные", "Սեղանի խաղեր", "Table games")),
    item("crash", same("Crash")),
  ],
  games: [
    ["golden-eclipse", "Golden Eclipse", "amusnet", "slots", 1],
    ["crystal-path", "Crystal Path", "amusnet", "slots", 1],
    ["midnight-star", "Midnight Star", "pragmatic-play", "table", 2],
    ["neon-crown", "Neon Crown", "amatic", "table", 3],
    ["royal-orbit", "Royal Orbit", "pragmatic-play", "table", 4],
    ["silver-rush", "Silver Rush", "amatic", "crash", 5],
  ].map(([id, name, provider, category, n]) =>
    item(id, same(name), {
      provider,
      category,
      image: `/images/game-${n}.webp`,
      url: "",
      mode: "iframe",
      featured: true,
      description: tr(
        "Предварительный обзор игры. Запуск станет доступен после подключения ссылки провайдера.",
        "Խաղի նախադիտում։ Գործարկումը հասանելի կլինի մատակարարի հղումը միացնելուց հետո։",
        "Game preview. Launch will be available when the provider link is connected.",
      ),
    }),
  ),
  slides: [
    item(
      "welcome",
      tr(
        "Ваша территория.\nВаши правила.",
        "Ձեր տարածքը։\nՁեր կանոնները։",
        "Your world.\nYour rules.",
      ),
      {
        image: "/images/hero.webp",
        label: tr(
          "ДОБРО ПОЖАЛОВАТЬ В YVNBET",
          "ԲԱՐԻ ԳԱԼՈՒՍՏ YVNBET",
          "WELCOME TO YVNBET",
        ),
        description: tr(
          "Знакомые игры. Новые впечатления. Всё начинается с вашего выбора.",
          "Ծանոթ խաղեր։ Նոր տպավորություններ։ Ամեն ինչ սկսվում է ձեր ընտրությունից։",
          "Familiar games. New experiences. It all starts with your choice.",
        ),
        button: tr(
          "Открыть коллекцию",
          "Բացել հավաքածուն",
          "Explore the collection",
        ),
        url: "/slots",
      },
    ),
    item(
      "discovery",
      tr(
        "Найдите свою\nновую классику.",
        "Գտեք ձեր\nնոր դասականը։",
        "Find your\nnext classic.",
      ),
      {
        image: "/images/game-2.webp",
        label: tr(
          "ИГРЫ И ПРОВАЙДЕРЫ",
          "ԽԱՂԵՐ ԵՎ ՄԱՏԱԿԱՐԱՐՆԵՐ",
          "GAMES & PROVIDERS",
        ),
        description: tr(
          "Откройте каталог и выберите свой ритм игры.",
          "Բացեք կատալոգը և ընտրեք ձեր խաղի ռիթմը։",
          "Explore the library and find your own rhythm.",
        ),
        button: tr("Смотреть игры", "Դիտել խաղերը", "View games"),
        url: "/slots",
      },
    ),
    item(
      "club",
      tr(
        "Всегда\nна вашей стороне.",
        "Միշտ\nձեր կողքին։",
        "Always\nby your side.",
      ),
      {
        image: "/images/game-4.webp",
        label: tr("ПОДДЕРЖКА YVNBET", "YVNBET ԱՋԱԿՑՈՒԹՅՈՒՆ", "YVNBET SUPPORT"),
        description: tr(
          "Поможем с регистрацией, доступом и вопросами по платформе.",
          "Կօգնենք գրանցման, մուտքի և հարթակի հարցերով։",
          "Here to help with registration, access and platform questions.",
        ),
        button: tr("Связаться с нами", "Կապվել մեզ հետ", "Get in touch"),
        url: "/help",
      },
    ),
  ],
  promotions: [
    item(
      "welcome-guide",
      tr(
        "Ваш первый шаг в YvnBet",
        "Ձեր առաջին քայլը YvnBet-ում",
        "Your first step into YvnBet",
      ),
      {
        kind: "news",
        image: "/images/hero.webp",
        start: "",
        end: "",
        description: tr(
          "Зарегистрируйтесь через форму на сайте. Оператор в Telegram поможет с доступом и расскажет об актуальных предложениях.",
          "Գրանցվեք կայքի ձևի միջոցով։ Telegram-ի օպերատորը կօգնի մուտքի հարցում և կներկայացնի ընթացիկ առաջարկները։",
          "Register using the website form. Our Telegram operator will help with access and explain current offers.",
        ),
        button: tr("Связаться", "Կապվել", "Contact us"),
        url: "/help",
      },
    ),
  ],
  faq: [
    item(
      "registration",
      tr("Как зарегистрироваться?", "Ինչպե՞ս գրանցվել։", "How do I register?"),
      {
        description: tr(
          "Нажмите «Регистрация», заполните форму и перейдите в Telegram. Отправьте подготовленное сообщение оператору.",
          "Սեղմեք «Գրանցվել», լրացրեք ձևը և անցեք Telegram։ Պատրաստված հաղորդագրությունն ուղարկեք օպերատորին։",
          "Choose Register, complete the form and continue to Telegram. Send the prepared message to the operator.",
        ),
      },
    ),
    item(
      "launch",
      tr("Как открыть игру?", "Ինչպե՞ս բացել խաղը։", "How do I open a game?"),
      {
        description: tr(
          "Выберите игру в каталоге. На её странице нажмите «Играть». Если встроенное окно не загружается, используйте кнопку открытия в новой вкладке.",
          "Ընտրեք խաղը կատալոգում և սեղմեք «Խաղալ»։ Եթե ներկառուցված պատուհանը չի բեռնվում, բացեք նոր ներդիրում։",
          "Select a game and choose Play. If the embedded platform does not load, use Open in a new tab.",
        ),
      },
    ),
    item(
      "support",
      tr(
        "Как связаться с поддержкой?",
        "Ինչպե՞ս կապվել աջակցության հետ։",
        "How can I contact support?",
      ),
      {
        description: tr(
          "Используйте кнопку Telegram в правом нижнем углу сайта.",
          "Օգտագործեք կայքի ներքևի աջ անկյունի Telegram կոճակը։",
          "Use the Telegram button at the bottom right of the website.",
        ),
      },
    ),
  ],
  pages: [
    item("about", tr("О нас", "Մեր մասին", "About us"), {
      description: tr(
        "YvnBet — место для знакомства с играми и провайдерами. Выбирайте игру, изучайте предложения и обращайтесь к нашей поддержке.",
        "YvnBet-ը խաղերին և մատակարարներին ծանոթանալու վայր է։ Ընտրեք խաղը, ուսումնասիրեք առաջարկները և կապվեք աջակցության հետ։",
        "YvnBet is a place to discover games and providers. Explore the collection and contact our support team.",
      ),
    }),
    item(
      "privacy",
      tr(
        "Политика конфиденциальности",
        "Գաղտնիության քաղաքականություն",
        "Privacy policy",
      ),
      {
        description: tr(
          "Для ответа на заявку сохраняются имя, телефон и Telegram. Доступ к заявкам есть у уполномоченных сотрудников. При переходе в Telegram данные добавляются в черновик сообщения; отправку подтверждаете вы. Для запроса удаления данных обратитесь в поддержку. Это предварительный текст: реквизиты оператора и сроки хранения необходимо указать до запуска.",
          "Հայտին պատասխանելու համար պահպանվում են անունը, հեռախոսը և Telegram-ը։ Հայտերին հասանելիություն ունեն լիազորված աշխատակիցները։ Telegram անցնելիս տվյալները հայտնվում են հաղորդագրության սևագրում. ուղարկումը հաստատում եք դուք։ Ջնջման համար կապվեք աջակցության հետ։ Նախնական տեքստ. օպերատորի տվյալներն ու պահպանման ժամկետները պետք է լրացվեն մինչև մեկնարկը։",
          "We save your name, phone number and Telegram handle to respond to your request. Authorised staff can access requests. Continuing to Telegram prepares a message draft; you decide whether to send it. Contact support to request deletion. This is draft copy: operator details and retention periods must be added before launch.",
        ),
      },
    ),
    item(
      "terms",
      tr("Условия использования", "Օգտագործման պայմաններ", "Terms of use"),
      {
        description: tr(
          "Сайт доступен лицам старше 18 лет. Условия отдельных игр и предложений определяются соответствующим провайдером. Перед использованием ознакомьтесь с его правилами. Текст для предварительного просмотра; финальные условия предоставляет оператор.",
          "Կայքը հասանելի է 18 տարեկանից բարձր անձանց։ Խաղերի և առաջարկների պայմանները սահմանում է համապատասխան մատակարարը։ Օգտագործելուց առաջ ծանոթացեք նրա կանոններին։ Նախնական տեքստ. վերջնական պայմանները տրամադրում է օպերատորը։",
          "This website is for adults aged 18 and over. Individual game and offer terms are set by the relevant provider. Read their rules before use. Preview copy; final terms must be supplied by the operator.",
        ),
      },
    ),
    item(
      "app",
      tr("YvnBet всегда рядом", "YvnBet-ը միշտ մոտ է", "Take YvnBet with you"),
      {
        description: tr(
          "Ваша коллекция игр в удобном мобильном формате.",
          "Ձեր խաղերի հավաքածուն՝ հարմար բջջային ձևաչափով։",
          "Your game collection in a convenient mobile format.",
        ),
      },
    ),
  ],
};
export function activePromotion(p, now = Date.now()) {
  return (
    p.enabled &&
    (!p.start || Date.parse(p.start) <= now) &&
    (!p.end || Date.parse(p.end + "T23:59:59Z") >= now)
  );
}
export function publicContent(c) {
  const out = structuredClone(c);
  for (const key of [
    "providers",
    "categories",
    "games",
    "slides",
    "promotions",
    "faq",
    "pages",
  ])
    out[key] = out[key].filter((x) => x.enabled);
  out.games = out.games.filter(
    (g) =>
      out.providers.some((p) => p.id === g.provider) &&
      out.categories.some((p) => p.id === g.category),
  );
  out.promotions = out.promotions.filter((p) => activePromotion(p));
  return out;
}
